# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6ee29015934061625999159742b4b989625b6413bff55ad681fb3a40e88195a0e965fcc80b00174ad5ac974c283ab2a3da3b24c2a0c4dbff8f2ee7ffd037505d

test:
  secret_key_base: 72abb4d651b67353fb43315f7505e82378097f37cf8395cd5fdb5ed5a2c40475e91a4c8d65a617d33f92185439a62711e3e5650c82aa4dab27f41eaa57d4d608

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
